name: CI/CD Pipeline

on:
  push:
    branches:
      - cicd-pipeline  # Runs when code is pushed to 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/back:latest ./back
          docker push ${{ secrets.DOCKER_USERNAME }}/back:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/front:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vm_yad_tamar_private_key.pem
          chmod 600 ~/.ssh/vm_yad_tamar_private_key.pem
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # cd /path/to/app
            # git pull origin main
            # docker-compose pull
            # docker-compose up -d --build
            cat "einav" > ~./einav.txt
          EOF